BEGIN
  FOR t IN (
    SELECT table_name
      FROM user_tables
     WHERE table_name IN (
       'ASSIGNMENT_SUBMISSION', 'REPLY', 'CHAPTER_PROGRESS', 'NOTICE', 'QNA',
       'LEAVE_REQUEST', 'ASSIGNMENT', 'CHAPTER', 'ENROLLMENT', 'COURSE_TARGET',
       'COURSE', 'ATTACHMENT', 'MEMBER', 'DEPARTMENT', 'POSITION'
     )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

BEGIN
  FOR s IN (
    SELECT sequence_name
      FROM user_sequences
     WHERE sequence_name IN (
       'SEQ_SNO', 'SEQ_PNO', 'SEQ_RNO', 'SEQ_QNO', 'SEQ_NNO', 'SEQ_LNO',
       'SEQ_ASNO', 'SEQ_CHNO', 'SEQ_HNO', 'SEQ_ENO', 'SEQ_ANO', 'SEQ_CNO',
       'SEQ_MNO'
     )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
  END LOOP;
END;
/

CREATE SEQUENCE SEQ_MNO NOCACHE;
CREATE SEQUENCE SEQ_CNO NOCACHE;
CREATE SEQUENCE SEQ_ANO NOCACHE;
CREATE SEQUENCE SEQ_ENO NOCACHE;
CREATE SEQUENCE SEQ_HNO NOCACHE;
CREATE SEQUENCE SEQ_CHNO NOCACHE;
CREATE SEQUENCE SEQ_ASNO NOCACHE;
-- CREATE SEQUENCE SEQ_LNO NOCACHE;
CREATE SEQUENCE SEQ_NNO NOCACHE;
CREATE SEQUENCE SEQ_QNO NOCACHE;
CREATE SEQUENCE SEQ_RNO NOCACHE;
CREATE SEQUENCE SEQ_PNO NOCACHE;
CREATE SEQUENCE SEQ_SNO NOCACHE;

CREATE TABLE DEPARTMENT (
  DEPARTMENT_ID VARCHAR2(3) PRIMARY KEY,
  DEPARTMENT_NAME VARCHAR2(100) NOT NULL UNIQUE,
  STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  CHECK (STATUS IN ('Y', 'N'))
);

COMMENT ON TABLE DEPARTMENT IS '부서';
COMMENT ON COLUMN DEPARTMENT.DEPARTMENT_ID IS '부서ID/D1~/PK';
COMMENT ON COLUMN DEPARTMENT.DEPARTMENT_NAME IS '부서명/2글자 이상 한글/UNIQUE';
COMMENT ON COLUMN DEPARTMENT.STATUS IS 'Y/N';

CREATE TABLE POSITION (
  POSITION_ID VARCHAR2(3) PRIMARY KEY,
  POSITION_NAME VARCHAR2(50) NOT NULL UNIQUE,
  POSITION_LEVEL NUMBER NOT NULL,
  STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  CHECK (STATUS IN ('Y', 'N'))
);

COMMENT ON TABLE POSITION IS '직급';
COMMENT ON COLUMN POSITION.POSITION_ID IS '직급ID/P1~/PK';
COMMENT ON COLUMN POSITION.POSITION_NAME IS '직급명/한글 직급 명/UNIQUE';
COMMENT ON COLUMN POSITION.POSITION_LEVEL IS '직급레벨/직급 높이';
COMMENT ON COLUMN POSITION.STATUS IS 'Y/N';

CREATE TABLE MEMBER (
  MEMBER_ID NUMBER PRIMARY KEY,
  LOGIN_ID VARCHAR2(20) NOT NULL UNIQUE,
  LOGIN_PWD VARCHAR2(20) NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(100) NOT NULL,
  PHONE VARCHAR2(13) NOT NULL,
  ADDRESS VARCHAR2(255) NOT NULL,
  HIRE_DATE DATE NOT NULL,
  RETIRE_DATE DATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  DEPARTMENT_ID VARCHAR2(3),
  POSITION_ID VARCHAR2(3),
  ROLE VARCHAR2(1) NOT NULL,
  PWD_RESET_DATE DATE,
  CHECK (STATUS IN ('Y', 'R', 'N')),
  CHECK (ROLE IN ('N', 'S', 'R')),
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID),
  FOREIGN KEY (POSITION_ID) REFERENCES POSITION (POSITION_ID)
);

COMMENT ON TABLE MEMBER IS '사원';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '사원ID/1부터 정수/PK';
COMMENT ON COLUMN MEMBER.LOGIN_ID IS 'ID/20글자 이하/UNIQUE';
COMMENT ON COLUMN MEMBER.LOGIN_PWD IS 'PASSWORD/8~20글자(암호화)';
COMMENT ON COLUMN MEMBER.NAME IS '사원명/2글자 이상 한글';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일/@포함된 전체 이메일 주소';
COMMENT ON COLUMN MEMBER.PHONE IS '연락처/- 포함 13글자';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소/한글 전체 주소';
COMMENT ON COLUMN MEMBER.HIRE_DATE IS '입사일/날짜, 시간';
COMMENT ON COLUMN MEMBER.RETIRE_DATE IS '퇴사일/날짜, 시간';
COMMENT ON COLUMN MEMBER.STATUS IS '상태값/재직(Y)/휴직(R)/퇴사(N)';
COMMENT ON COLUMN MEMBER.DEPARTMENT_ID IS '부서ID/부서 FK';
COMMENT ON COLUMN MEMBER.POSITION_ID IS '직급ID/직급 FK';
COMMENT ON COLUMN MEMBER.ROLE IS '권한코드/사원(N)/관리자(S)/인사(R)';
COMMENT ON COLUMN MEMBER.PWD_RESET_DATE IS '비밀번호초기화일시/날짜, 시간';

CREATE TABLE ATTACHMENT (
  FILE_ID NUMBER PRIMARY KEY,
  ORIGINAL_NAME VARCHAR2(200) NOT NULL,
  CHANGED_NAME VARCHAR2(200) NOT NULL,
  FILE_PATH VARCHAR2(500) NOT NULL,
  FILE_SIZE NUMBER NOT NULL,
  TYPE VARCHAR2(10) NOT NULL,
  VIDEO_DURATION NUMBER,
  MEMBER_ID NUMBER NOT NULL,
  STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  UPLOAD_DATE DATE DEFAULT SYSDATE NOT NULL,
  CHECK (STATUS IN ('Y', 'N')),
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

COMMENT ON TABLE ATTACHMENT IS '첨부파일';
COMMENT ON COLUMN ATTACHMENT.FILE_ID IS '파일ID/1부터 정수/PK';
COMMENT ON COLUMN ATTACHMENT.ORIGINAL_NAME IS '원본파일명/원본 이름 그대로';
COMMENT ON COLUMN ATTACHMENT.CHANGED_NAME IS '저장파일명/저장된 파일 이름/UNIQUE';
COMMENT ON COLUMN ATTACHMENT.FILE_PATH IS '파일경로/파일 저장 절대 경로';
COMMENT ON COLUMN ATTACHMENT.FILE_SIZE IS '파일크기/정수(BYTE)';
COMMENT ON COLUMN ATTACHMENT.TYPE IS '파일유형/확장자 이름';
COMMENT ON COLUMN ATTACHMENT.VIDEO_DURATION IS '영상길이초/영상 길이(초)';
COMMENT ON COLUMN ATTACHMENT.MEMBER_ID IS '사원ID/등록자 FK';
COMMENT ON COLUMN ATTACHMENT.STATUS IS '상태값/Y/N';
COMMENT ON COLUMN ATTACHMENT.UPLOAD_DATE IS '업로드일시/날짜,시간';

CREATE TABLE COURSE (
  COURSE_ID NUMBER PRIMARY KEY,
  COURSE_TITLE VARCHAR2(50) NOT NULL,
  DESCRIPTION VARCHAR2(2000),
  MEMBER_ID NUMBER,
  STATUS VARCHAR2(1) DEFAULT 'W' NOT NULL,
  START_DATE DATE,
  END_DATE DATE,
  TOTAL_HOURS NUMBER,
  CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_DATE DATE DEFAULT SYSDATE,
  CHECK (STATUS IN ('W', 'Y', 'N')),
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

COMMENT ON TABLE COURSE IS '강의';
COMMENT ON COLUMN COURSE.COURSE_ID IS '강의ID/1부터 정수/PK';
COMMENT ON COLUMN COURSE.COURSE_TITLE IS '강의명';
COMMENT ON COLUMN COURSE.DESCRIPTION IS '강의설명';
COMMENT ON COLUMN COURSE.MEMBER_ID IS '사원ID/담당자 FK';
COMMENT ON COLUMN COURSE.STATUS IS '강의상태/예정(W)/진행중(Y)/종료(N)';
COMMENT ON COLUMN COURSE.START_DATE IS '강의시작일/날짜, 시간';
COMMENT ON COLUMN COURSE.END_DATE IS '강의종료일/날짜, 시간';
COMMENT ON COLUMN COURSE.TOTAL_HOURS IS '총강의시간/시간(H)';
COMMENT ON COLUMN COURSE.CREATE_DATE IS '생성일시/날짜, 시간';
COMMENT ON COLUMN COURSE.UPDATED_DATE IS '수정일시/날짜, 시간';

CREATE TABLE COURSE_TARGET (
  TARGET_ID VARCHAR2(5) PRIMARY KEY,
  COURSE_ID NUMBER NOT NULL,
  TARGET_TYPE VARCHAR2(6),
  TARGET_VALUE VARCHAR2(3),
  CHECK (TARGET_TYPE IS NULL OR TARGET_TYPE IN ('부서', '직급', '전체')),
  FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID)
);

COMMENT ON TABLE COURSE_TARGET IS '강의 대상 조건';
COMMENT ON COLUMN COURSE_TARGET.TARGET_ID IS '대상조건ID/T1~/PK';
COMMENT ON COLUMN COURSE_TARGET.COURSE_ID IS '강의ID/강의 FK';
COMMENT ON COLUMN COURSE_TARGET.TARGET_TYPE IS '대상유형/부서, 직급, 전체';
COMMENT ON COLUMN COURSE_TARGET.TARGET_VALUE IS '대상값/부서 ID , 직급 ID';

CREATE TABLE ASSIGNMENT (
  ASSIGNMENT_ID NUMBER PRIMARY KEY,
  COURSE_ID NUMBER NOT NULL,
  ASSIGNMENT_TITLE VARCHAR2(50) NOT NULL,
  DESCRIPTION VARCHAR2(2000),
  START_DATE DATE NOT NULL,
  DUE_DATE DATE NOT NULL,
  MAX_SCORE NUMBER NOT NULL,
  FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID)
);

COMMENT ON TABLE ASSIGNMENT IS '과제';
COMMENT ON COLUMN ASSIGNMENT.ASSIGNMENT_ID IS '과제ID/1부터 정수/PK';
COMMENT ON COLUMN ASSIGNMENT.COURSE_ID IS '강의ID/강의 FK';
COMMENT ON COLUMN ASSIGNMENT.ASSIGNMENT_TITLE IS '과제명';
COMMENT ON COLUMN ASSIGNMENT.DESCRIPTION IS '과제설명';
COMMENT ON COLUMN ASSIGNMENT.START_DATE IS '과제시작일/날짜, 시간';
COMMENT ON COLUMN ASSIGNMENT.DUE_DATE IS '과제마감일/날짜, 시간';
COMMENT ON COLUMN ASSIGNMENT.MAX_SCORE IS '최대 점수/만점';

/*
CREATE TABLE LEAVE_REQUEST (
  LEAVE_ID NUMBER PRIMARY KEY,
  MEMBER_ID NUMBER NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  TOTAL_DAYS NUMBER NOT NULL,
  REASON VARCHAR2(2000),
  STATUS VARCHAR2(20) DEFAULT '신청' NOT NULL,
  APPROVED_BY NUMBER,
  DENY_REASON VARCHAR2(1000),
  CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_DATE DATE DEFAULT SYSDATE NOT NULL,
  CHECK (STATUS IN ('신청', '승인', '반려', '취소')),
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
  FOREIGN KEY (APPROVED_BY) REFERENCES MEMBER (MEMBER_ID)
);

COMMENT ON TABLE LEAVE_REQUEST IS '연차';
COMMENT ON COLUMN LEAVE_REQUEST.LEAVE_ID IS '연차신청ID/1부터 숫자/PK';
COMMENT ON COLUMN LEAVE_REQUEST.MEMBER_ID IS '사원ID/신청자 FK';
COMMENT ON COLUMN LEAVE_REQUEST.START_DATE IS '연차시작일/날짜';
COMMENT ON COLUMN LEAVE_REQUEST.END_DATE IS '연차종료일/날짜';
COMMENT ON COLUMN LEAVE_REQUEST.TOTAL_DAYS IS '사용일수/숫자';
COMMENT ON COLUMN LEAVE_REQUEST.REASON IS '신청사유';
COMMENT ON COLUMN LEAVE_REQUEST.STATUS IS '상태값/신청(R)/승인(A)/반려(D)/취소(C)';
COMMENT ON COLUMN LEAVE_REQUEST.APPROVED_BY IS '사원ID/승인자 FK';
COMMENT ON COLUMN LEAVE_REQUEST.DENY_REASON IS '반려사유';
COMMENT ON COLUMN LEAVE_REQUEST.CREATED_DATE IS '신청일시/날짜, 시간';
COMMENT ON COLUMN LEAVE_REQUEST.UPDATED_DATE IS '수정일시/날짜, 시간';
*/

CREATE TABLE ENROLLMENT (
  ENROLLMENT_ID NUMBER PRIMARY KEY,
  MEMBER_ID NUMBER NOT NULL,
  COURSE_ID NUMBER NOT NULL,
  STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  START_DATE DATE DEFAULT SYSDATE,
  COMPLETED_DATE DATE,
  CHECK (STATUS IN ('Y', 'N')),
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
  FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID)
);

COMMENT ON TABLE ENROLLMENT IS '수강';
COMMENT ON COLUMN ENROLLMENT.ENROLLMENT_ID IS '수강ID/1부터 정수/PK';
COMMENT ON COLUMN ENROLLMENT.MEMBER_ID IS '사원ID/수강자 FK';
COMMENT ON COLUMN ENROLLMENT.COURSE_ID IS '강의ID/강의 FK';
COMMENT ON COLUMN ENROLLMENT.STATUS IS '수강상태/Y/N';
COMMENT ON COLUMN ENROLLMENT.START_DATE IS '수강시작일/날짜, 시간';
COMMENT ON COLUMN ENROLLMENT.COMPLETED_DATE IS '수강완료일/날짜, 시간';

CREATE TABLE CHAPTER (
  CHAPTER_ID NUMBER PRIMARY KEY,
  COURSE_ID NUMBER NOT NULL,
  CHAPTER_TITLE VARCHAR2(50) NOT NULL,
  CHAPTER_ORDER NUMBER NOT NULL,
  VIDEO_FILE_ID NUMBER,
  CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_DATE DATE DEFAULT SYSDATE NOT NULL,
  FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID),
  FOREIGN KEY (VIDEO_FILE_ID) REFERENCES ATTACHMENT (FILE_ID)
);

COMMENT ON TABLE CHAPTER IS '챕터';
COMMENT ON COLUMN CHAPTER.CHAPTER_ID IS '챕터ID/1부터 정수/PK';
COMMENT ON COLUMN CHAPTER.COURSE_ID IS '강의ID/강의 FK';
COMMENT ON COLUMN CHAPTER.CHAPTER_TITLE IS '챕터제목';
COMMENT ON COLUMN CHAPTER.CHAPTER_ORDER IS '챕터순서';
COMMENT ON COLUMN CHAPTER.VIDEO_FILE_ID IS '파일ID/영상 파일 FK';
COMMENT ON COLUMN CHAPTER.CREATE_DATE IS '생성일시/날짜, 시간';
COMMENT ON COLUMN CHAPTER.UPDATED_DATE IS '수정일시/날짜, 시간';

CREATE TABLE CHAPTER_PROGRESS (
  PROGRESS_ID NUMBER PRIMARY KEY,
  ENROLLMENT_ID NUMBER NOT NULL,
  CHAPTER_ID NUMBER NOT NULL,
  WATCHED_SECONDS NUMBER DEFAULT 0 NOT NULL,
  LAST_POSITION_SECONDS NUMBER DEFAULT 0 NOT NULL,
  CHAP_COMP_RATE NUMBER(5,2) DEFAULT 000.00 NOT NULL,
  IS_COMPLETED VARCHAR2(1) DEFAULT 'N' NOT NULL,
  CHECK (IS_COMPLETED IN ('Y', 'N')),
  FOREIGN KEY (ENROLLMENT_ID) REFERENCES ENROLLMENT (ENROLLMENT_ID),
  FOREIGN KEY (CHAPTER_ID) REFERENCES CHAPTER (CHAPTER_ID)
);

COMMENT ON TABLE CHAPTER_PROGRESS IS '챕터 이수';
COMMENT ON COLUMN CHAPTER_PROGRESS.PROGRESS_ID IS '진도ID/1부터 정수/PK';
COMMENT ON COLUMN CHAPTER_PROGRESS.ENROLLMENT_ID IS '수강ID/수강 FK';
COMMENT ON COLUMN CHAPTER_PROGRESS.CHAPTER_ID IS '챕터ID/챕터 FK';
COMMENT ON COLUMN CHAPTER_PROGRESS.WATCHED_SECONDS IS '시청시간초/시청 시간(초)';
COMMENT ON COLUMN CHAPTER_PROGRESS.LAST_POSITION_SECONDS IS '마지막위치초/마지막 시청 위치(초)';
COMMENT ON COLUMN CHAPTER_PROGRESS.CHAP_COMP_RATE IS '챕터이수율/챕터 이수율(%)/(시청시간/영상길이)';
COMMENT ON COLUMN CHAPTER_PROGRESS.IS_COMPLETED IS '완료여부/(Y/N)/챕터 진도율 90% 이상 시 Y';

CREATE TABLE QNA (
  QNA_ID NUMBER PRIMARY KEY,
  COURSE_ID NUMBER NOT NULL,
  FILE_ID NUMBER,
  MEMBER_ID NUMBER NOT NULL,
  QNA_TITLE VARCHAR2(50) NOT NULL,
  CONTENT VARCHAR2(2000),
  IS_PRIVATE VARCHAR2(1) DEFAULT 'N' NOT NULL,
  CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_DATE DATE DEFAULT SYSDATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  CHECK (IS_PRIVATE IN ('Y', 'N')),
  CHECK (STATUS IN ('Y', 'N')),
  FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID),
  FOREIGN KEY (FILE_ID) REFERENCES ATTACHMENT (FILE_ID),
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

COMMENT ON TABLE QNA IS '강의 QnA';
COMMENT ON COLUMN QNA.QNA_ID IS 'QNAID/1부터 정수/PK';
COMMENT ON COLUMN QNA.COURSE_ID IS '강의ID/강의 FK';
COMMENT ON COLUMN QNA.FILE_ID IS '파일ID/첨부파일 FK';
COMMENT ON COLUMN QNA.MEMBER_ID IS '사원ID/작성자 FK';
COMMENT ON COLUMN QNA.QNA_TITLE IS 'QNA제목';
COMMENT ON COLUMN QNA.CONTENT IS 'QNA내용';
COMMENT ON COLUMN QNA.IS_PRIVATE IS '비공개여부/(Y/N)';
COMMENT ON COLUMN QNA.CREATED_DATE IS '작성일시/날짜, 시간';
COMMENT ON COLUMN QNA.UPDATED_DATE IS '수정일시/날짜, 시간';
COMMENT ON COLUMN QNA.STATUS IS '상태값/게시 상태(Y/N)';

CREATE TABLE REPLY (
  REPLY_ID NUMBER PRIMARY KEY,
  QNA_ID NUMBER NOT NULL,
  MEMBER_ID NUMBER NOT NULL,
  PARENT_REPLY_ID NUMBER,
  CONTENT VARCHAR2(1000) NOT NULL,
  CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_DATE DATE DEFAULT SYSDATE,
  STATE VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  CHECK (STATE IN ('Y', 'N')),
  FOREIGN KEY (QNA_ID) REFERENCES QNA (QNA_ID),
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
  FOREIGN KEY (PARENT_REPLY_ID) REFERENCES REPLY (REPLY_ID)
);

COMMENT ON TABLE REPLY IS 'QnA 답글';
COMMENT ON COLUMN REPLY.REPLY_ID IS '답글ID/1부터 정수/PK';
COMMENT ON COLUMN REPLY.QNA_ID IS 'QNAID/QnA FK';
COMMENT ON COLUMN REPLY.MEMBER_ID IS '사원ID/작성자 FK';
COMMENT ON COLUMN REPLY.PARENT_REPLY_ID IS '부모답글ID/부모 답글 FK';
COMMENT ON COLUMN REPLY.CONTENT IS '답글내용';
COMMENT ON COLUMN REPLY.CREATED_DATE IS '작성일시/날짜, 시간';
COMMENT ON COLUMN REPLY.UPDATED_DATE IS '수정일시/날짜, 시간';
COMMENT ON COLUMN REPLY.STATE IS '상태값/(Y/N)';

CREATE TABLE NOTICE (
  NOTICE_ID NUMBER PRIMARY KEY,
  NOTICE_TITLE VARCHAR2(50) NOT NULL,
  CONTENT VARCHAR2(2000),
  MEMBER_ID NUMBER NOT NULL,
  COUNT NUMBER DEFAULT 0 NOT NULL,
  CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_DATE DATE DEFAULT SYSDATE NOT NULL,
  FILE_ID NUMBER,
  STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  CHECK (STATUS IN ('Y', 'N')),
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
  FOREIGN KEY (FILE_ID) REFERENCES ATTACHMENT (FILE_ID)
);

COMMENT ON TABLE NOTICE IS '공지사항';
COMMENT ON COLUMN NOTICE.NOTICE_ID IS '공지ID/1부터 정수/PK';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '공지제목';
COMMENT ON COLUMN NOTICE.CONTENT IS '공지내용';
COMMENT ON COLUMN NOTICE.MEMBER_ID IS '사원ID/작성자 FK';
COMMENT ON COLUMN NOTICE.COUNT IS '조회수';
COMMENT ON COLUMN NOTICE.CREATED_DATE IS '작성일시/날짜, 시간';
COMMENT ON COLUMN NOTICE.UPDATED_DATE IS '수정일시/날짜, 시간';
COMMENT ON COLUMN NOTICE.FILE_ID IS '파일ID/첨부파일 FK';
COMMENT ON COLUMN NOTICE.STATUS IS '상태값/게시 상태(Y/N)';

CREATE TABLE ASSIGNMENT_SUBMISSION (
  SUBMISSION_ID NUMBER PRIMARY KEY,
  ASSIGNMENT_ID NUMBER NOT NULL,
  MEMBER_ID NUMBER NOT NULL,
  CONTENT VARCHAR2(2000),
  FILE_ID NUMBER,
  SCORE NUMBER,
  STATUS NUMBER DEFAULT 1 NOT NULL,
  SUBMITTED_DATE DATE DEFAULT SYSDATE NOT NULL,
  CHECK (STATUS IN (1, 2, 3, 4)),
  FOREIGN KEY (ASSIGNMENT_ID) REFERENCES ASSIGNMENT (ASSIGNMENT_ID),
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
  FOREIGN KEY (FILE_ID) REFERENCES ATTACHMENT (FILE_ID)
);

COMMENT ON TABLE ASSIGNMENT_SUBMISSION IS '과제 제출 정보';
COMMENT ON COLUMN ASSIGNMENT_SUBMISSION.SUBMISSION_ID IS '제출ID/1부터 정수/PK';
COMMENT ON COLUMN ASSIGNMENT_SUBMISSION.ASSIGNMENT_ID IS '과제ID/과제 FK';
COMMENT ON COLUMN ASSIGNMENT_SUBMISSION.MEMBER_ID IS '사원ID/제출자 FK';
COMMENT ON COLUMN ASSIGNMENT_SUBMISSION.CONTENT IS '제출내용';
COMMENT ON COLUMN ASSIGNMENT_SUBMISSION.FILE_ID IS '파일ID/첨부파일 FK';
COMMENT ON COLUMN ASSIGNMENT_SUBMISSION.SCORE IS '점수';
COMMENT ON COLUMN ASSIGNMENT_SUBMISSION.STATUS IS '(제출여부/채점여부)/1(제출 전), 2(제출 완료), 3(채점 전), 4(채점 완료)';
COMMENT ON COLUMN ASSIGNMENT_SUBMISSION.SUBMITTED_DATE IS '제출일시/날짜, 시간';

COMMIT;