-- COURSE 테이블에 20개의 더미 데이터 삽입
INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (1, 'Java Basics 101', 'Intro to Java syntax, variables, and control flow.', NULL, 'Y', TO_DATE('2026-06-03', 'YYYY-MM-DD'), TO_DATE('2026-06-28', 'YYYY-MM-DD'), 24, SYSDATE - 20, SYSDATE - 20);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (2, 'Java OOP Practice', 'Classes, objects, inheritance, polymorphism, and design exercises.', NULL, 'Y', TO_DATE('2026-06-10', 'YYYY-MM-DD'), TO_DATE('2026-07-05', 'YYYY-MM-DD'), 30, SYSDATE - 19, SYSDATE - 19);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (3, 'Spring Core Fundamentals', 'Dependency injection and bean lifecycle with hands-on labs.', NULL, 'W', TO_DATE('2026-07-01', 'YYYY-MM-DD'), TO_DATE('2026-07-30', 'YYYY-MM-DD'), 32, SYSDATE - 18, SYSDATE - 18);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (4, 'Spring MVC Starter', 'Controller, view resolver, and request mapping basics.', NULL, 'Y', TO_DATE('2026-05-20', 'YYYY-MM-DD'), TO_DATE('2026-06-20', 'YYYY-MM-DD'), 28, SYSDATE - 17, SYSDATE - 17);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (5, 'Spring Boot First App', 'Build and run a web app with Spring Boot and Maven.', NULL, 'N', TO_DATE('2026-04-01', 'YYYY-MM-DD'), TO_DATE('2026-04-30', 'YYYY-MM-DD'), 22, SYSDATE - 16, SYSDATE - 16);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (6, 'Oracle SQL Essentials', 'SELECT, JOIN, GROUP BY, and practical SQL query exercises.', NULL, 'Y', TO_DATE('2026-06-05', 'YYYY-MM-DD'), TO_DATE('2026-07-01', 'YYYY-MM-DD'), 26, SYSDATE - 15, SYSDATE - 15);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (7, 'Advanced SQL Tuning', 'Execution plans, indexing strategy, and SQL optimization basics.', NULL, 'W', TO_DATE('2026-08-01', 'YYYY-MM-DD'), TO_DATE('2026-08-25', 'YYYY-MM-DD'), 20, SYSDATE - 14, SYSDATE - 14);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (8, 'JSP and JSTL Workshop', 'JSP page composition and JSTL core/functions usage.', NULL, 'Y', TO_DATE('2026-05-25', 'YYYY-MM-DD'), TO_DATE('2026-06-22', 'YYYY-MM-DD'), 24, SYSDATE - 13, SYSDATE - 13);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (9, 'Servlet API Deep Dive', 'Request/response lifecycle, session handling, and filters.', NULL, 'N', TO_DATE('2026-03-10', 'YYYY-MM-DD'), TO_DATE('2026-04-05', 'YYYY-MM-DD'), 18, SYSDATE - 12, SYSDATE - 12);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (10, 'REST API with Spring', 'Design REST endpoints and JSON responses using Spring MVC.', NULL, 'Y', TO_DATE('2026-06-12', 'YYYY-MM-DD'), TO_DATE('2026-07-12', 'YYYY-MM-DD'), 34, SYSDATE - 11, SYSDATE - 11);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (11, 'JavaScript for Backend Devs', 'DOM basics and AJAX flow for Spring MVC projects.', NULL, 'Y', TO_DATE('2026-06-15', 'YYYY-MM-DD'), TO_DATE('2026-07-08', 'YYYY-MM-DD'), 16, SYSDATE - 10, SYSDATE - 10);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (12, 'jQuery AJAX Hands-on', '$.ajax request patterns with JSON response rendering.', NULL, 'W', TO_DATE('2026-07-20', 'YYYY-MM-DD'), TO_DATE('2026-08-10', 'YYYY-MM-DD'), 14, SYSDATE - 9, SYSDATE - 9);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (13, 'MyBatis Mapper Basics', 'Mapper XML, namespace, resultType, and parameter binding.', NULL, 'Y', TO_DATE('2026-06-18', 'YYYY-MM-DD'), TO_DATE('2026-07-15', 'YYYY-MM-DD'), 21, SYSDATE - 8, SYSDATE - 8);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (14, 'MyBatis Pagination', 'RowBounds and offset-limit pagination examples.', NULL, 'Y', TO_DATE('2026-06-22', 'YYYY-MM-DD'), TO_DATE('2026-07-20', 'YYYY-MM-DD'), 19, SYSDATE - 7, SYSDATE - 7);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (15, 'Git Workflow for Teams', 'Branch strategy, pull requests, and conflict resolution.', NULL, 'N', TO_DATE('2026-02-14', 'YYYY-MM-DD'), TO_DATE('2026-03-01', 'YYYY-MM-DD'), 12, SYSDATE - 6, SYSDATE - 6);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (16, 'Linux and Deployment Basics', 'Server basics, process management, and deployment checklist.', NULL, 'W', TO_DATE('2026-08-03', 'YYYY-MM-DD'), TO_DATE('2026-08-31', 'YYYY-MM-DD'), 25, SYSDATE - 5, SYSDATE - 5);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (17, 'Web Security Starter', 'Session security, CSRF basics, and input validation.', NULL, 'Y', TO_DATE('2026-06-26', 'YYYY-MM-DD'), TO_DATE('2026-07-26', 'YYYY-MM-DD'), 27, SYSDATE - 4, SYSDATE - 4);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (18, 'Testing Spring Applications', 'JUnit tests for service and controller layers.', NULL, 'Y', TO_DATE('2026-06-30', 'YYYY-MM-DD'), TO_DATE('2026-07-22', 'YYYY-MM-DD'), 17, SYSDATE - 3, SYSDATE - 3);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (19, 'Project Architecture Review', 'Layered architecture and package design guidelines.', NULL, 'W', TO_DATE('2026-07-25', 'YYYY-MM-DD'), TO_DATE('2026-08-18', 'YYYY-MM-DD'), 15, SYSDATE - 2, SYSDATE - 2);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (20, 'Capstone Team Project', 'Team-based mini project from planning to deployment.', NULL, 'Y', TO_DATE('2026-06-01', 'YYYY-MM-DD'), TO_DATE('2026-07-31', 'YYYY-MM-DD'), 40, SYSDATE - 1, SYSDATE - 1);

-- COMMIT;

-- 더미 삭제
-- DELETE FROM COURSE WHERE COURSE_ID BETWEEN 1 AND 20;
-- COMMIT;

-- COURSE 테이블에 추가 더미 데이터 30개 삽입 (21 ~ 50)
INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (21, 'Frontend HTML Basics', 'Core HTML tags and semantic structure for web pages.', NULL, 'Y', TO_DATE('2026-07-02', 'YYYY-MM-DD'), TO_DATE('2026-07-20', 'YYYY-MM-DD'), 12, SYSDATE - 30, SYSDATE - 30);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (22, 'Frontend CSS Essentials', 'Selectors, box model, layout and responsive basics.', NULL, 'Y', TO_DATE('2026-07-03', 'YYYY-MM-DD'), TO_DATE('2026-07-23', 'YYYY-MM-DD'), 14, SYSDATE - 29, SYSDATE - 29);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (23, 'Frontend JavaScript Basics', 'Variables, functions, arrays and DOM handling.', NULL, 'Y', TO_DATE('2026-07-04', 'YYYY-MM-DD'), TO_DATE('2026-07-25', 'YYYY-MM-DD'), 16, SYSDATE - 28, SYSDATE - 28);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (24, 'jQuery Practical Guide', 'Event handling and AJAX requests with jQuery.', NULL, 'W', TO_DATE('2026-08-01', 'YYYY-MM-DD'), TO_DATE('2026-08-20', 'YYYY-MM-DD'), 10, SYSDATE - 27, SYSDATE - 27);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (25, 'Java Collections Deep Dive', 'List, Set, Map and practical collection usage.', NULL, 'Y', TO_DATE('2026-07-06', 'YYYY-MM-DD'), TO_DATE('2026-07-30', 'YYYY-MM-DD'), 20, SYSDATE - 26, SYSDATE - 26);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (26, 'Java Exception Handling', 'Checked and unchecked exceptions with best practices.', NULL, 'N', TO_DATE('2026-05-01', 'YYYY-MM-DD'), TO_DATE('2026-05-18', 'YYYY-MM-DD'), 8, SYSDATE - 25, SYSDATE - 25);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (27, 'Spring Boot REST APIs', 'Build CRUD APIs and response handling patterns.', NULL, 'Y', TO_DATE('2026-07-08', 'YYYY-MM-DD'), TO_DATE('2026-08-05', 'YYYY-MM-DD'), 24, SYSDATE - 24, SYSDATE - 24);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (28, 'Spring Validation', 'Request validation and error response formatting.', NULL, 'Y', TO_DATE('2026-07-10', 'YYYY-MM-DD'), TO_DATE('2026-07-29', 'YYYY-MM-DD'), 12, SYSDATE - 23, SYSDATE - 23);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (29, 'Spring Security Intro', 'Authentication and authorization basics.', NULL, 'W', TO_DATE('2026-08-05', 'YYYY-MM-DD'), TO_DATE('2026-08-28', 'YYYY-MM-DD'), 18, SYSDATE - 22, SYSDATE - 22);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (30, 'MyBatis Dynamic SQL', 'if, choose, foreach usage in mapper XML.', NULL, 'Y', TO_DATE('2026-07-12', 'YYYY-MM-DD'), TO_DATE('2026-08-02', 'YYYY-MM-DD'), 16, SYSDATE - 21, SYSDATE - 21);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (31, 'Oracle SQL Joins', 'Inner join, outer join and multi-table joins.', NULL, 'Y', TO_DATE('2026-07-13', 'YYYY-MM-DD'), TO_DATE('2026-07-31', 'YYYY-MM-DD'), 14, SYSDATE - 20, SYSDATE - 20);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (32, 'Oracle Aggregation', 'Group by, having and advanced aggregation patterns.', NULL, 'N', TO_DATE('2026-05-03', 'YYYY-MM-DD'), TO_DATE('2026-05-22', 'YYYY-MM-DD'), 10, SYSDATE - 19, SYSDATE - 19);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (33, 'PLSQL Basics', 'Anonymous blocks and control statements in PLSQL.', NULL, 'Y', TO_DATE('2026-07-15', 'YYYY-MM-DD'), TO_DATE('2026-08-06', 'YYYY-MM-DD'), 18, SYSDATE - 18, SYSDATE - 18);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (34, 'Git and GitHub Workflow', 'Commit strategy, branch model and pull request flow.', NULL, 'Y', TO_DATE('2026-07-16', 'YYYY-MM-DD'), TO_DATE('2026-08-01', 'YYYY-MM-DD'), 9, SYSDATE - 17, SYSDATE - 17);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (35, 'Linux CLI for Developers', 'Essential shell commands for development workflow.', NULL, 'W', TO_DATE('2026-08-10', 'YYYY-MM-DD'), TO_DATE('2026-08-29', 'YYYY-MM-DD'), 11, SYSDATE - 16, SYSDATE - 16);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (36, 'Docker Basics', 'Container fundamentals and image lifecycle.', NULL, 'Y', TO_DATE('2026-07-18', 'YYYY-MM-DD'), TO_DATE('2026-08-08', 'YYYY-MM-DD'), 13, SYSDATE - 15, SYSDATE - 15);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (37, 'REST API Documentation', 'OpenAPI and API documentation best practices.', NULL, 'Y', TO_DATE('2026-07-19', 'YYYY-MM-DD'), TO_DATE('2026-08-09', 'YYYY-MM-DD'), 8, SYSDATE - 14, SYSDATE - 14);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (38, 'Unit Testing with JUnit', 'Unit testing patterns for service and utility classes.', NULL, 'Y', TO_DATE('2026-07-20', 'YYYY-MM-DD'), TO_DATE('2026-08-11', 'YYYY-MM-DD'), 15, SYSDATE - 13, SYSDATE - 13);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (39, 'Integration Testing', 'Controller and repository integration tests.', NULL, 'W', TO_DATE('2026-08-12', 'YYYY-MM-DD'), TO_DATE('2026-08-30', 'YYYY-MM-DD'), 12, SYSDATE - 12, SYSDATE - 12);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (40, 'Clean Code Principles', 'Readable code, naming and refactoring basics.', NULL, 'N', TO_DATE('2026-04-10', 'YYYY-MM-DD'), TO_DATE('2026-04-28', 'YYYY-MM-DD'), 10, SYSDATE - 11, SYSDATE - 11);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (41, 'Design Patterns Intro', 'Factory, strategy and singleton examples.', NULL, 'Y', TO_DATE('2026-07-22', 'YYYY-MM-DD'), TO_DATE('2026-08-13', 'YYYY-MM-DD'), 17, SYSDATE - 10, SYSDATE - 10);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (42, 'Data Modeling Basics', 'Entity relationship modeling and normalization.', NULL, 'Y', TO_DATE('2026-07-23', 'YYYY-MM-DD'), TO_DATE('2026-08-12', 'YYYY-MM-DD'), 14, SYSDATE - 9, SYSDATE - 9);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (43, 'Performance Tuning 101', 'JVM and SQL performance tuning checklist.', NULL, 'W', TO_DATE('2026-08-14', 'YYYY-MM-DD'), TO_DATE('2026-09-03', 'YYYY-MM-DD'), 16, SYSDATE - 8, SYSDATE - 8);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (44, 'Caching Strategies', 'Application caching with practical cache patterns.', NULL, 'Y', TO_DATE('2026-07-25', 'YYYY-MM-DD'), TO_DATE('2026-08-16', 'YYYY-MM-DD'), 11, SYSDATE - 7, SYSDATE - 7);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (45, 'Message Queue Basics', 'Asynchronous processing and queue fundamentals.', NULL, 'Y', TO_DATE('2026-07-26', 'YYYY-MM-DD'), TO_DATE('2026-08-18', 'YYYY-MM-DD'), 12, SYSDATE - 6, SYSDATE - 6);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (46, 'Cloud Intro for Developers', 'Cloud service models and deployment concepts.', NULL, 'N', TO_DATE('2026-03-01', 'YYYY-MM-DD'), TO_DATE('2026-03-20', 'YYYY-MM-DD'), 9, SYSDATE - 5, SYSDATE - 5);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (47, 'Kubernetes Primer', 'Pods, deployments and service exposure basics.', NULL, 'W', TO_DATE('2026-08-18', 'YYYY-MM-DD'), TO_DATE('2026-09-07', 'YYYY-MM-DD'), 15, SYSDATE - 4, SYSDATE - 4);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (48, 'API Security Essentials', 'Token-based auth and secure endpoint design.', NULL, 'Y', TO_DATE('2026-07-28', 'YYYY-MM-DD'), TO_DATE('2026-08-20', 'YYYY-MM-DD'), 13, SYSDATE - 3, SYSDATE - 3);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (49, 'Code Review Workshop', 'Pull request review process and quality checklist.', NULL, 'Y', TO_DATE('2026-07-29', 'YYYY-MM-DD'), TO_DATE('2026-08-21', 'YYYY-MM-DD'), 8, SYSDATE - 2, SYSDATE - 2);

INSERT INTO COURSE (COURSE_ID, COURSE_TITLE, DESCRIPTION, MEMBER_ID, STATUS, START_DATE, END_DATE, TOTAL_HOURS, CREATE_DATE, UPDATED_DATE)
VALUES (50, 'Capstone Final Sprint', 'Final sprint planning, demo prep and retrospective.', NULL, 'Y', TO_DATE('2026-07-30', 'YYYY-MM-DD'), TO_DATE('2026-08-25', 'YYYY-MM-DD'), 20, SYSDATE - 1, SYSDATE - 1);

COMMIT;

-- 전체 더미 삭제
-- DELETE FROM COURSE WHERE COURSE_ID BETWEEN 1 AND 50;
-- COMMIT;